//
// Created by Alex Hubitski on 12/8/24.
//

#ifndef QMK_FIRMWARE_CONFIG_H
#define QMK_FIRMWARE_CONFIG_H

#endif // QMK_FIRMWARE_CONFIG_H

#define AUTO_SHIFT_TIMEOUT 175
#define NO_AUTO_SHIFT_TAB

#define DEBOUNCE 36
#define REPEAT_DELAY 200
#define TAP_HOLD 200

#define ONESHOT_TAP_TOGGLE 3

#define TAPPING_FORCE_HOLD

#undef IGNORE_MOD_TAP_INTERRUPT

#define MOUSEKEY_INTERVAL 27
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 47
